# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://kcema.net
title: KcEMA
email: kcema.alliance@gmail.com
author: KcEMA
description: > # "Write an awesome description for your new site here. 
  Kansas City Electronic Music and Arts Alliance (KcEMA) was founded in 2007
  and works to support and develop the electronic music and arts community in Kansas City.
copyright: 'Copyright &copy; 2016 KcEMA. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Twitter
    url: https://twitter.com/kcemalliance
  - title: Facebook
    url: https://www.facebook.com/KCEMAlliance/
  - title: YouTube
    url: https://www.youtube.com/user/KCEMAlliance



